# Generated by Django 2.0.5 on 2018-07-18 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPuntuacion',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='puntuacion',
            old_name='Documento',
            new_name='documento',
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='cliente_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repositorio.ClienteBot'),
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='cliente_web',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repositorio.ClienteWeb'),
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='tipo_puntuacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='repositorio.TipoPuntuacion'),
            preserve_default=False,
        ),
    ]
