# Generated by Django 2.0.5 on 2018-07-18 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0002_auto_20180718_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_usuario', models.CharField(max_length=32)),
                ('id_usuario', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='cliente_bot',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='cliente_web',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='tipo_puntuacion',
        ),
        migrations.RenameModel(
            old_name='TipoPuntuacion',
            new_name='TipoCliente',
        ),
        migrations.DeleteModel(
            name='ClienteBot',
        ),
        migrations.DeleteModel(
            name='ClienteWeb',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.TipoCliente'),
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='repositorio.Cliente'),
            preserve_default=False,
        ),
    ]
